---
title: "Seminarska naloga 2"
author: "Alen Kahteran"
date: '20. 11. 2020'
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
params:
  printcode: yes
  printresults: hide
editor_options:
  chunk_output_type: console
---

```{r, setup, include=FALSE}
# set this option in the first code chunk in the document
knitr::opts_chunk$set(echo = params$printcode, results= params$printresults, warning = FALSE)
# importing required library
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r, echo=FALSE, eval=TRUE, results="markup", fig.align="center"}

full_data <- as_tibble(read.table("test_data/pn2020.csv",
                                  header = TRUE,
                                  fill = TRUE,
                                  sep = ";",
                                  encoding = "WIN-1250",
                                  dec=","))



#  19, 41, 214

set.seed(8)

data_500 <- sample_n(full_data, 500)

filter(count(full_data, ZaporednaStevilkaPN), n==1)
filter(full_data, ZaporednaStevilkaPN %in% filter(count(full_data, ZaporednaStevilkaPN), n==1)$ZaporednaStevilkaPN)
asdf <- filter(full_data, ZaporednaStevilkaPN %in% filter(count(full_data, ZaporednaStevilkaPN), n==1)$ZaporednaStevilkaPN)
table(asdf$Spol)
t.test(alkoholicari_full$VrednostAlkotesta ~ alkoholicari_full$Spol, var.equal=FALSE, paired=FALSE)


```
